### ISSUE TITLE
Global prefix config for keyframes 

### ISSUE THREAD

**Issue by asins** [madebysource/lesshat#103]
I set 
@ms : false;

But I still will be generated - o - content
e.g.

``` css
.keyframes(~'lightSpeedOut, 0% {transform: translateY(0%) scale(1); opacity: 1 } 100% {transform: translateY(5px) scale(.9); opacity: .4 }');
to
@-o-keyframes lightSpeedOut {
    0% {
        -o-transform: translateY(0%) scale(1);
        opacity: 1
    }
    100% {
        -o-transform: translateY(5px) scale(.9);
        opacity: .4
    }
}
...
```
