### ISSUE TITLE
Wrong tail for the .keyframes

### ISSUE THREAD

**Issue by zvictor** [madebysource/lesshat#108]
### Description

On the `.keyframes` mixin the last characters seem to be wrong for me. Except by the `@keyframes` section, all the vendor specific definitions end with a `}}` string, but the  `@keyframes` tail is compound by a `};\n}` sequence. Isn't that wrong?
### Error

When using `.keyframe` on a Meteorjs project it breaks the entire application and we have the following error:

``` haskell
=> Errors prevented startup:

While building the application:
client/animate.less.css: @keyframes missing '}' near line 6:266
```
### Input

``` css
.keyframes(~'animationName, 0%{ transform: scale(1.5); color: blue; } 100%{ transform: scale(2); color: red }');
```
### Output

``` css
lesshat-selector {
  -lh-property: 0; } 
@-webkit-keyframes animationName{ 0%{ -webkit-transform: scale(1.5); color: blue; } 100%{ -webkit-transform: scale(2); color: red }}
@-moz-keyframes animationName{ 0%{ -moz-transform: scale(1.5); color: blue; } 100%{ -moz-transform: scale(2); color: red }}
@-o-keyframes animationName{ 0%{ -o-transform: scale(1.5); color: blue; } 100%{ -o-transform: scale(2); color: red }}
@keyframes animationName{ 0%{-webkit-transform: scale(1.5);-moz-transform: scale(1.5);-ms-transform: scale(1.5);transform: scale(1.5); color: blue; } 100%{-webkit-transform: scale(2);-moz-transform: scale(2);-ms-transform: scale(2);transform: scale(2); color: red };
}
```
