### ISSUE TITLE
prefixed attributes (e.g. transform) in animation

### ISSUE THREAD

**Issue by szepeviktor** [madebysource/lesshat#119]
Do you have a solution for

``` css
@<PREFIX>keyframes {
    <PREFIX>transform: rotate(360deg);
}
```

that prevents all prefixes selectors × all prefixes attributes version?
Like

``` css
@-webkit-keyframes {
    -o-transform: rotate(360deg);
}
```
