### ISSUE TITLE
.background-image() with multiple background images

### ISSUE THREAD

**Issue by bonzai** [madebysource/lesshat#12]
I'm using LESS Hat 1.1.1.

I want to use multiple background images - logo on top of a gradient:

``` css
.container {
    .background-image(~'url(logo.png), linear-gradient(to bottom, #181b1e, #272d33)');
}
```

but as you can see, the result is incorrect (svg is not encoded in base64):

``` css
.container {
    background-image: url(logo.png),url(data:image/svg+xml;base64,<?xml version="1.0" ?><svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 1 1" preserveAspectRatio="none"><linearGradient id="grad-ucgg-generated" gradientUnits="userSpaceOnUse" x1="0%" y1="0%" x2="0%" y2="100%"><stop offset="0%" stop-color="#181b1e" stop-opacity="1"/><stop offset="100%" stop-color="#272d33" stop-opacity="1"/></linearGradient><rect x="0" y="0" width="1" height="1" fill="url(#grad-ucgg-generated)" /></svg>);
    background-image: url(logo.png),-moz-linear-gradient(top, #181b1e, #272d33);
    background-image: url(logo.png),-webkit-linear-gradient(top, #181b1e, #272d33);
    background-image: url(logo.png),-o-linear-gradient(top, #181b1e, #272d33);
    background-image: url(logo.png),linear-gradient(to bottom, #181b1e, #272d33);
}
```
