### ISSUE TITLE
sticky position mixin

### ISSUE THREAD

**Issue by woneob** [madebysource/lesshat#154]
How about add this one?

```css
div {
    position: -webkit-sticky;
    position: -moz-sticky;
    position: -ms-sticky;
    position: -o-sticky;
    position: sticky;
    top: 0;
}
```

http://updates.html5rocks.com/2012/08/Stick-your-landings-position-sticky-lands-in-WebKit
http://red-team-design.com/position-sticky-might-be-the-next-best-thing/
