### ISSUE TITLE
background-image with gradient and url

### ISSUE THREAD

**Issue by tregusti** [madebysource/lesshat#16]
With this snippet:

``` css
#a { .background-image( linear-gradient(to bottom, green, black), url(bg.png) ); }
#b { .background-image( linear-gradient(to bottom, green, black) ); }
```

I get this:

``` css
#a {
  background-image: url(data:image/svg+xml;base64,[PD94bWwgdmVyc2lvbj0iMS4wIiA/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiB2aWV3Qm94PSIwIDAgMSAxIiBwcmVzZXJ2ZUFzcGVjdFJhdGlvPSJub25lIj48bGluZWFyR3JhZGllbnQgaWQ9ImdyYWQtdWNnZy1nZW5lcmF0ZWQiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIiB4MT0iMCUiIHkxPSIwJSIgeDI9IjAlIiB5Mj0iMTAwJSI+PHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iIzAwODAwMCIgc3RvcC1vcGFjaXR5PSIxIi8+PHN0b3Agb2Zmc2V0PSI1MCUiIHN0b3AtY29sb3I9IiMwMDAwMDAiIHN0b3Atb3BhY2l0eT0iMSIvPil1cmwoYmcucG5nKTwvbGluZWFyR3JhZGllbnQ+PHJlY3QgeD0iMCIgeT0iMCIgd2lkdGg9IjEiIGhlaWdodD0iMSIgZmlsbD0idXJsKCNncmFkLXVjZ2ctZ2VuZXJhdGVkKSIgLz48L3N2Zz4=);
  background-image: -moz-linear-gradient(top, #008000, #000000), url(bg.png);
  background-image: -webkit-linear-gradient(top, #008000, #000000), url(bg.png);
  background-image: -o-linear-gradient(top, #008000, #000000), url(bg.png);
  background-image: linear-gradient(to bottom, #008000, #000000), url(bg.png);
}
#b {
  background-image: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiB2aWV3Qm94PSIwIDAgMSAxIiBwcmVzZXJ2ZUFzcGVjdFJhdGlvPSJub25lIj48bGluZWFyR3JhZGllbnQgaWQ9ImdyYWQtdWNnZy1nZW5lcmF0ZWQiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIiB4MT0iMCUiIHkxPSIwJSIgeDI9IjAlIiB5Mj0iMTAwJSI+PHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iIzAwODAwMCIgc3RvcC1vcGFjaXR5PSIxIi8+PHN0b3Agb2Zmc2V0PSIxMDAlIiBzdG9wLWNvbG9yPSIjMDAwMDAwIiBzdG9wLW9wYWNpdHk9IjEiLz48L2xpbmVhckdyYWRpZW50PjxyZWN0IHg9IjAiIHk9IjAiIHdpZHRoPSIxIiBoZWlnaHQ9IjEiIGZpbGw9InVybCgjZ3JhZC11Y2dnLWdlbmVyYXRlZCkiIC8+PC9zdmc+);
  background-image: -moz-linear-gradient(top, #008000, #000000);
  background-image: -webkit-linear-gradient(top, #008000, #000000);
  background-image: -o-linear-gradient(top, #008000, #000000);
  background-image: linear-gradient(to bottom, #008000, #000000);
}
```

And the generated SVG for #a decodes to this:

``` xml
<?xml version="1.0" ?>
<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 1 1" preserveAspectRatio="none">
    <linearGradient id="grad-ucgg-generated" gradientUnits="userSpaceOnUse" x1="0%" y1="0%" x2="0%" y2="100%">
        <stop offset="0%" stop-color="#008000" stop-opacity="1"/><stop offset="50%" stop-color="#000000" stop-opacity="1"/>)url(bg.png)
    </linearGradient>
    <rect x="0" y="0" width="1" height="1" fill="url(#grad-ucgg-generated)" />
</svg>
```

The url is merged into the SVG instead of as a separate background value.

With a build script as per #15, I would have sent a pull request your way =)
