### ISSUE TITLE
Text-overflow mixin

### ISSUE THREAD

**Issue by nicooprat** [madebysource/lesshat#64]
Feature request ! Something like :

``` css
.text-overflow(@value: ellipsis) {
    text-overflow: @value;
    white-space: nowrap;
    overflow: hidden;
}
```

According to http://www.w3schools.com/cssref/css3_pr_text-overflow.asp it should not need any vendor prefix.
