### ISSUE TITLE
Font smoothing

### ISSUE THREAD

**Issue by nicooprat** [madebysource/lesshat#65]
Feature request !

``` css
.font-smoothing( @smoothing: antialiased ) {
    font-smoothing: @smoothing;
    -ms-font-smoothing: @smoothing;
    -moz-font-smoothing: @smoothing;
    -webkit-font-smoothing: @smoothing;
    -o-font-smoothing: @smoothing;
}
```

This property is still ambiguous... The official spec is `font-smooth` but is not supported anywhere (https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth). Only Webkit supports its own variation `webkit-font-smoothing` for now.

So the global support is not huge but this property is very useful. I use it by default on the `body` with the `antialiased` value on every project now (instead of default `subpixel-antialiased`) because the rendering is much better imo.

A mixin would simplify updates for future potential W3C standards changes, don't you think ? I'm not sure about other vendor prefixes though... Also wondering if it would be better to write `font-smooth` instead of `font-smoothing`...
