### ISSUE TITLE
Basic gradients

### ISSUE THREAD

**Issue by nicooprat** [madebysource/lesshat#66]
Feature request !

Because I was only using very basic CSS gradients in most of my designs, I wrote some shorthand for vertical, horizontal and radial 2 steps gradients. Here's what I use for now :

``` css
.gradient-vertical( @start_color , @end_color ) {
    background-image: linear-gradient( center bottom, @end_color 0%, @start_color 100% );
    background-image: -ms-linear-gradient( center bottom, @end_color 0%, @start_color 100% );
    background-image: -moz-linear-gradient( center bottom, @end_color 0%, @start_color 100% );
    background-image: -webkit-gradient( linear, 0% 0%, 0% 100%, from( @start_color ), to( @end_color ) );
    background-image: -o-linear-gradient( center bottom, @end_color 0%, @start_color 100% );
}

.gradient-horizontal( @start_color , @end_color ) {
    background-image: linear-gradient( left center, @end_color 0%, @start_color 100% );
    background-image: -ms-linear-gradient( left center, @end_color 0%, @start_color 100% );
    background-image: -moz-linear-gradient( left center, @end_color 0%, @start_color 100% );
    background-image: -webkit-gradient( linear, 0% 0%, 100% 0%, from( @start_color ), to( @end_color ) );
    background-image: -o-linear-gradient( left center, @end_color 0%, @start_color 100% );
}

.gradient-radial( @start_color , @end_color ) {
    background-image: -webkit-radial-gradient(50% 50%, ellipse cover, @start_color, @end_color 100%);
    background-image: -moz-radial-gradient(50% 50%, ellipse cover, @start_color, @end_color 100%);
    background-image: -o-radial-gradient(50% 50%, ellipse cover, @start_color, @end_color 100%);
    background-image: -ms-radial-gradient(50% 50%, ellipse cover, @start_color, @end_color 100%);
    background-image: radial-gradient(50% 50%, ellipse cover, @start_color, @end_color 100%);
}
```

I know there's already a `.background-image()` mixin, but those ones are much easier to write and remember. What do you think ?
