### ISSUE TITLE
Using @variable to .gradient (~"image-1[, image-2, ..., image-n]");

### ISSUE THREAD

**Issue by gabovanlugo** [madebysource/lesshat#7]
Let me explain with an example:

``` css
// init

@primary: red;
@secondary: blue;

nav{
    .gradient(~"linear-gradient(0deg, @primary 0%, @secondary 100%)");
}


It compiles into:
nav{
    background-image: linear-gradient(0deg,@primary 0, @secondary 100%);
}

// end
```

Is there a way to make this mixin working with declared less variables?
