### ISSUE TITLE
Code includes a space when compiled where there should be none.

### ISSUE THREAD

**Issue by justStand** [madebysource/lesshat#74]
Less Code:

``` less
#id{
  li{
    .animationone{
      .animation(animation-name 1s linear infinite);
    }
  }
}
```

Desired Output:

``` less
#id li.animationone {
  -webkit-animation: animation-name 1s linear infinite;
  -moz-animation: animation-name 1s linear infinite;
  -o-animation: animation-name 1s linear infinite;
  animation: animation-name 1s linear infinite;
}
```

Actual Output:

``` less
#id li .animationone {
  -webkit-animation: animation-name 1s linear infinite;
  -moz-animation: animation-name 1s linear infinite;
  -o-animation: animation-name 1s linear infinite;
  animation: animation-name 1s linear infinite;
}
```
