### ISSUE TITLE
.display mixin

### ISSUE THREAD

**Issue by deepfriedmind** [madebysource/lesshat#75]
In the documentation it says this is the output:

``` css
div {
 .display(flex);
}

// Result
div {
 display: -webkit-box;
 display: -ms-flexbox;
 display: -webkit-flex;
 display: -moz-box;
} 
```

What I'm getting is:

``` css
div {
    .lh-display(flex);
}

// Result
div {
      display: -ms-flexbox;
      display: flex;
}
```

...which means it's not working in Safari. Am I doing something wrong? I haven't changed any of the defaults in the global prefix configuration, and I see the `.lh-display` mixin has the following variables:

``` scss
  @oldwebkit_local: true;
  @moz_local: true;
  @webkit_local: true;
  @ms_local: true;
  @w3c_local: true;
```
