### ISSUE TITLE
Wrong output for .align-items mixin

### ISSUE THREAD

**Issue by deepfriedmind** [madebysource/lesshat#78]
Hi,

When using the `.align-items` mixin with `flex-end` as value, I get the following output:

``` css
div {
    -webkit-box-align: flex-end;
    -moz-box-align: end;
    -webkit-align-items: end;
    -ms-flex-align: flex-end;
    align-items: flex-end;
}
```

This doesn't work in either IE10 or Safari.

Here is what the output should be ([source](http://philipwalton.github.io/solved-by-flexbox/demos/grids/)):

``` css
div {
    -webkit-box-align: end;
    -webkit-align-items: flex-end;
    -moz-box-align: end;
    -ms-flex-align: end;
    align-items: flex-end;
}
```

I haven't tried other values for this mixin yet, but I'm guessing `flex-start` would have the same issues.
