### ISSUE TITLE
.keyframes gives incorrect output - additional semi-colon

### ISSUE THREAD

**Issue by Nospamas** [madebysource/lesshat#86]
Given input (from the docs):

``` less
.keyframes(~'animationName, 0%{ transform: scale(1.5); color: blue; } 100%{ transform: scale(2); color: red }');
```

Gives output (from my processor using lesshat.less version 2.0.15):

``` css
lesshat-selector {
  -lh-property: 0; } 
@-webkit-keyframes animationName{ 0%{ -webkit-transform: scale(1.5); color: blue; } 100%{ -webkit-transform: scale(2); color: red }}
@-moz-keyframes animationName{ 0%{ -moz-transform: scale(1.5); color: blue; } 100%{ -moz-transform: scale(2); color: red }}
@-o-keyframes animationName{ 0%{ -o-transform: scale(1.5); color: blue; } 100%{ -o-transform: scale(2); color: red }}
@keyframes animationName{ 0%{-webkit-transform: scale(1.5);-moz-transform: scale(1.5);-ms-transform: scale(1.5);transform: scale(1.5); color: blue; } 100%{-webkit-transform: scale(2);-moz-transform: scale(2);-ms-transform: scale(2);transform: scale(2); color: red };
}
```

The problem is that final semi colon. It appears to me to be invalid css. Interestingly this does match what the docs say it will output, if you add a couple of line breaks.
